version: "3.7"
services:
  node-app:
    container_name: wonder-guide-container
    build: .
    volumes:
      - ./Natours:/app/src:ro
    ports:
      - "2000:2000"
    env_file:
      - ./Natours/config.env
