services:
  node-app:
    container_name: wonder-guide-container
    ports:
      - "2000:2000"
    env_file:
      - ./Natours/config.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
