services:
  node-app:
    container_name: wonder-guide-container
    ports:
      - "2000:2000"
    env_file:
      - ./Natours/config.env

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
