version: "3.7"
services:
  node-app:
    build:
      context: .
      target: development
    volumes:
      - ./Natours:/app/src:ro
    environment:
      - NODE_ENV=development
    command: npm start
